name: Continuous Integration

on:
  push:
    branches: [ master, 'feature/**', 'hotfix/**', 'fix/**' ]
    paths:
      - '**.java'
      - 'build.gradle.kts'
      - '.github/workflows/**.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**.java'
      - 'build.gradle.kts'

permissions:
  contents: read
  pull-requests: read

jobs:
  test-build:
    uses: ./.github/workflows/test-build.yml
