name: Continuous Integration
on:
  workflow_call:
  
permissions:
  contents: read
  pull-requests: read

jobs:
  build-gradle:
    name: Build Gradle artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
  build-docker:
    name: Build docker image
    runs-on: ubuntu-lastest
    needs: ['build-gradle']
    steps:
      - uses: actions/checkout@v3
